import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <a href="/">Home</a>
            <a href="/what-we-offer">What We Offer</a>
            <a href="/why-sunniva">Why Sunniva</a>
            <a href="/installer">Installers</a>
            <a href="/shop">Shop</a>
            <a href="/contact-us">Contact Us</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
