import Link from 'next/link'
import { useRouter } from 'next/router'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const router = useRouter()

  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <Link href="/" passHref>
              <a className={router.pathname === '/' ? 'active' : ''}>Home</a>
            </Link>
            <Link href="/what-we-offer" passHref>
              <a
                className={router.pathname === '/what-we-offer' ? 'active' : ''}
              >
                What We Offer
              </a>
            </Link>
            <Link href="/why-sunniva" passHref>
              <a className={router.pathname === '/why-sunniva' ? 'active' : ''}>
                Why Sunniva
              </a>
            </Link>
            <Link href="/installer" passHref>
              <a className={router.pathname === '/installer' ? 'active' : ''}>
                Installers
              </a>
            </Link>
            <Link href="/shop" passHref>
              <a className={router.pathname === '/shop' ? 'active' : ''}>
                Shop
              </a>
            </Link>
            <Link href="/contact-us" passHref>
              <a className={router.pathname === '/contact-us' ? 'active' : ''}>
                Contact Us
              </a>
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
